name: Jest

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  jest:
    name: Run Jest
    runs-on: Ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install project
        run: npm install
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test 
          --transformIgnorePatterns "node_modules/(?!axios)/"

